### ISSUE TITLE
Wrongly treating latex math as text in Polish

### ISSUE THREAD

**Issue by tomasz-brak** [ltex-plus/vscode-ltex-plus#170]
**Describe the bug**
When using the pl.PL language LTEX doesn't exclude the commands and math equations from spell checking

<img width="2092" height="482" alt="Image" src="https://github.com/user-attachments/assets/d21e6f28-22e0-4a2a-bc4e-5c9c20f83a90" />

**Steps to reproduce**
1. Open any polish document containing latex syntax for example
```latex
\documentclass{article}
\usepackage[a4paper, margin=1in]{geometry}
\usepackage{polski}

\title{Test}
\author{}
\date{}

\begin{document}
\maketitle

\section*{Przykład}
\begin{math}
\varepsilon = \frac{a}{b}
\end{math}

Tu jest błąd, składnia \LaTeX interpretowana jako tekst.

\end{document}
```

**Expected behavior**
No error here this is correct

**LTeX+ configuration**
```json
  "ltex.language": "pl-PL",
  "latex-workshop.latex.autoClean.run": "onSucceeded",
  "ltex.additionalRules.motherTongue": "pl-PL",
  "ltex.additionalRules.enablePickyRules": true,
  "ltex.ltex-ls.path": "C:\\Users\\tomasz\\Documents\\dev\\ltex",
  "ltex.completionEnabled": true,
  "ltex.diagnosticSeverity": "information"
```

```
REPLACE_THIS_WITH_LTEX_CONFIGURATION
```

</details>

**"LTeX+ Language Server" log file**
First, reproduce the bug. Then, go to `View` → `Output` and select `LTeX Language Server` in the drop-down list. Paste this log here:

<details>

```
REPLACE_THIS_WITH_LTEX_LANGUAGE_SERVER_LOG
```

</details>

**"LTeX+ Language Client" log file**
First, set the `ltex.trace.server` setting in your `settings.json` to `"verbose"`. Then, reload the VS Code window and reproduce the bug. Go to `View` → `Output` and select `LTeX Language Client` in the drop-down list. Paste this log here (note: it will contain your checked document):

<details>

```
REPLACE_THIS_WITH_LTEX_LANGUAGE_CLIENT_LOG
```

</details>

**Version information**
List here the version information of the relevant software.

- vscode-ltex-plus: 15.6.1

{
  "ltex-ls": "18.6.1",
  "java": "21.0.3"
}

**Comment by spitzerd** [comment]
Fixed. You can start testing using the upcoming nightly release.

**Comment by tomasz-brak** [comment]
I don't think it solved the problem, still having issuses on `15.7.0-alpha.nightly.2025-12-17`

<img width="381" height="198" alt="Image" src="https://github.com/user-attachments/assets/7087a2dc-6ebb-4542-a9f7-5687c296b602" />

<img width="918" height="276" alt="Image" src="https://github.com/user-attachments/assets/6a4d3916-7ebf-45f1-bb32-395a8fe3ceee" />

**Comment by spitzerd** [comment]
It works for me.
Please check if `ltex.ltex-ls.path` is set in your settings.json. If this is the case, remove  `ltex.ltex-ls.path` 

<img width="934" height="811" alt="Image" src="https://github.com/user-attachments/assets/e2f39848-fb62-43f7-91ec-d2673944f26e" />

**Comment by tomasz-brak** [comment]
You were right! I see the translated `atrapa` now. But i still see some dummys not detected and quotes in latex syntax read as normal text

i leave a more comprehensive test document:

```tex

\documentclass{article}
\usepackage[a4paper, margin=1in]{geometry}
\usepackage{polski}
\usepackage{amsmath}

\title{Test}
\author{}
\date{}

\begin{document}
\maketitle

\section*{Przykład}
\begin{math}
\varepsilon = \frac{a}{b}
\end{math}

Tu jest błąd, składnia \LaTeX interpretowana jako tekst.

\textbf{Zadanie 5.}
\begin{itemize}
    \item[a)] Symbol $\left[\frac{0}{0}\right]$. $H \xrightarrow{} \lim \frac{e^x + e^{-x} - 2}{1 - \cos x} \left[\frac{0}{0}\right] \xrightarrow{H} \lim \frac{e^x - e^{-x}}{\sin x} \left[\frac{0}{0}\right] \xrightarrow{H} \lim \frac{e^x + e^{-x}}{\cos x} = \frac{1+1}{1} = 2$.
    \item[b)] $\lim_{x \to \infty} \frac{\frac{\pi}{2} - \text{arctg } x}{\frac{1}{x}} \left[\frac{0}{0}\right] \xrightarrow{H} \lim \frac{-\frac{1}{1+x^2}}{-\frac{1}{x^2}} = \lim \frac{x^2}{1+x^2} = 1$.
\end{itemize}


\end{document}
```

<img width="940" height="176" alt="Image" src="https://github.com/user-attachments/assets/116ab5ad-c5d3-4c4c-b89c-38c3116d1692" />

<img width="841" height="99" alt="Image" src="https://github.com/user-attachments/assets/7e00a42f-85ae-446a-9adf-de1e13d216ab" />

**Comment by spitzerd** [comment]
See https://ltex-plus.github.io/ltex-plus/faq.html#how-can-i-prevent-text-in-math-mode-from-producing-false-positives

The LaTeX parser is not perfect and it won't be perfect anytime soon. See https://github.com/ltex-plus/vscode-ltex-plus/blob/develop/CONTRIBUTING.md#known-issues-and-limitations

**Comment by tomasz-brak** [comment]
Ok, thanks
